# Generated by Django 2.0.4 on 2020-06-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidApparel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='')),
                ('product_name', models.TextField()),
                ('product_price', models.CharField(max_length=200, null=True)),
                ('product_offer', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'kidapparels',
            },
        ),
        migrations.CreateModel(
            name='MenApparel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='')),
                ('product_name', models.TextField()),
                ('product_price', models.CharField(max_length=200, null=True)),
                ('product_offer', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'menapparels',
            },
        ),
        migrations.CreateModel(
            name='womenApparel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='')),
                ('product_name', models.TextField()),
                ('product_price', models.CharField(max_length=200, null=True)),
                ('product_offer', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'womenapparels',
            },
        ),
    ]
