# Generated by Django 3.0.7 on 2020-07-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='images')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('organisation', models.CharField(max_length=200)),
                ('Intro', models.TextField(max_length=200)),
                ('selfie', models.ImageField(null=True, upload_to='images')),
                ('document', models.FileField(upload_to='documents')),
                ('contact', models.BigIntegerField(null=True)),
                ('CIN', models.BigIntegerField(null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('mssg', models.TextField(max_length=200)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200, null=True)),
                ('company_type', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=200)),
                ('Locations', models.CharField(max_length=250, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('website', models.CharField(max_length=200)),
                ('selfie', models.ImageField(null=True, upload_to='images')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('Industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
    ]
